### ISSUE TITLE
Inquire the list of sensor ID

### ISSUE THREAD

**Issue by kvmduc** [AprLie/TrafficStream#2]
I found it difficult to reproduce the dataset, which has the number of nodes increasing every year. I’m trying to reproduce your dataset with some modifications.

I would like to inquire about the list of sensor IDs that you selected each year, like DCRNN’s authors [DCRNN sensor IDs](https://github.com/liyaguang/DCRNN/blob/master/data/sensor_graph/graph_sensor_ids.txt)

I’m eager to receive your feedback.

Thanks a lot!

**Comment by AprLie** [comment]
Hi @kvmduc, thank you for your attention.  Could you give me your email address so that I can send your the sensor ID file?

**Comment by kvmduc** [comment]
> Hi @kvmduc, thank you for your attention. Could you give me your email address so that I can send your the sensor ID file?

My email: kvmduc3@gmail.com
Thanks for your support
